platform :ios, '11.0'
use_frameworks!

target 'Clique' do
    #pod 'SDWebImage', '~>3.7'
    #pod 'SwiftyJSON'
    #pod 'youtube-ios-player-helper', '~> 0.1'
    #pod 'Soundcloud'
    #pod 'SVGPlayButton', '~> 0.4'
    #pod 'Alamofire-Synchronous', :git => 'https://github.com/Dalodd/Alamofire-Synchronous.git'
    #pod 'Alamofire', '~> 3.4'
    
    #pod 'BTNavigationDropdownMenu'
    pod 'SwipeableTabBarController', '~> 1.0'
    pod 'Alamofire', '~> 4.6'
    pod 'AlamofireImage', '~> 3.3'
    pod 'SwiftyJSON', '~> 4.0'
    
end
