platform :ios, '8.0'
use_frameworks!

target 'Clique' do
    pod 'SDWebImage', '~>3.7'
    pod 'SwiftyJSON'
    pod 'youtube-ios-player-helper', '~> 0.1'
    pod 'Soundcloud'
    pod 'SVGPlayButton', '~> 0.4'
    pod 'Alamofire-Synchronous', :git => 'https://github.com/Dalodd/Alamofire-Synchronous.git'
    pod 'Alamofire', '~> 3.4'
end
